config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :rooms
  resources :members
  resources :calendars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  has_many :members
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :study, presence: true
  validates :time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :study, :time])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new
      if @member.save
        redirect_to root_path
      else
        render :new
      end
  end

  private
  def member_params
    params.require(:member).merge(user_id: current_user.id, room_id: @room.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.order("created_at DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
      if @room.save
        redirect_to root_path
      else
        render :new
      end
  end

  def show
  end

  private
  def room_params
    params.require(:room).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar">
        <h1 class="grid-6"><a href="/">LearningCalendar</a></h1>
        
          <div class="user_nav grid-6">
            <% if user_signed_in? %>
            <li><%= link_to current_user.name, "#", class: "user-name" %> </li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
            <% else%>
            <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
            <% end %>
          </div>
        
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p>
        Copyright  LearningCalendar2022.
      </p>
    </footer>
  </body>
</html>

app/views/members/new.html.erb
<div class="main">
  <div class='create-member-'>
    <h1>参加メンバー</h1>
    <div class="create-room">
    <%= form_with model: [@member], class: 'form', local: true do |f| %>
    <%= f.submit '送信', class: 'form-submit' %>
    <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="main">
  <div class="create-list">
    <div class="create-room">
      <%= link_to "ルームを作成する", new_room_path %>
    </div>

    <div class="rooms">
      <% @rooms.each do |room| %>
        <div class="room-name">
          <%= link_to room.name, room_path(id: room) %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/rooms/new.html.erb
<div class="main">
  <div class='create-room-new'>
    <h1>新規ルーム</h1>
    <%=form_with model: @room, local: true do |f|%>
      <div class='create-room-mane'>
        <%= f.label :name, :ルーム名, class: 'room-form'%>
      </div>
      <div class='create-room-in'>
        <%= f.text_field :name, class: 'room-form', placeholder: 'ルーム名を入力してください'%>
      </div>
      <div class='create-room-btn'>
        <%= f.submit class: 'room-form'%>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="main">
  <div class='create-room-show'>
    <h1>参加メンバー</h1>
    <div class="create-room">
      <%= link_to "参加する", new_member_path %>
    </div>
  </div>
</div>